site_name: CAMeL Lab Guidelines
repo_url: https://github.com/slkh/camel-guidelines
site_url: https://camel-guidelines.rtfd.io
site_author: Salam Khalifa
nav:
    - Home: index.md
    - Morphology: morphology.md
    - Phonology: phonology.md
    - Orthography: orthography.md
    - Syntax: syntax.md
    - Data: data.md
theme: 
    name: readthedocs
    custom_dir: custom_theme
markdown_extensions:
    - def_list
    - footnotes
    - tables
    - pymdownx.details
    - toc:
        permalink: True
    - attr_list

extra_css:
    - css/extra.css
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
  - javascripts/tables.js

plugins:
    - search:
        lang: ar
        lang: en
    - macros
    - add-number:
        order: 2
    - bibtex:
        bib_file: "refs.bib"
        cite_style: "pandoc"
        bib_command: "\\bib"

extra:
    issue_tracker: https://github.com/slkh/camel-guidelines/issues

