site_name: CAMeL Lab Guidelines
nav:
    - Home: index.md
    - Morphology: morphology.md
    - Phonology: phonology.md
    - Orthography: orthography.md
theme: 
    name: readthedocs
markdown_extensions:
  - footnotes
  - tables
extra_css:
    - extra.css
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
  - javascripts/tables.js