site_name: CAMeL Lab Guidelines
nav:
    - Home: index.md
    - Test1: test1.md
    - Topic1:
        - Test2: test2.md
    - Morphology: morphology.md
    - Phonology: phonology.md
    - Orthography: orthography.md
theme: 
    name: readthedocs
    navigation_depth: 4

extra_css:
    - extra.css